---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.backServiceName }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - name: http
      port: {{ .Values.global.backServicePort }}
      protocol: TCP
      targetPort: {{ .Values.containerPort }}
      nodePort: {{ .Values.nodePort }}
  selector:
    app: {{ .Chart.Name }}