{
 "title": "Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Frontend logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"frontend\"}"
    }
   ]
  },
  {
   "title": "ALB ingress log",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{control_plane=\"yc-alb-ingress-controller\"}"
    }
   ]
  },
  {
   "title": "Backend logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"backend\"}"
    }
   ]
  }
 ]
}
{
 "title": "monitoring",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Orders count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "orders_count{app=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum (requests_count{app=\"backend\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histogram response timing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(response_timing_ms_bucket{app=\"backend\"}[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests rate 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(requests_count{app=\"backend\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}