apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-ingress"
  annotations:
    ingress.alb.yc.io/subnets: {{ .Values.subnetId }}
    ingress.alb.yc.io/external-ipv4-address: {{ or .Values.externalAddr "auto" }}
    ingress.alb.yc.io/group-name: momo-alb-nginx
spec:
  tls:
  - hosts:
    - grafana.sausage-store.ru
    secretName: yc-certmgr-cert-id-{{ .Values.certId }}
  rules:
  - host: grafana.sausage-store.ru
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 3000
