apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: grafana
  sessionAffinity: None
  type: NodePort
  ports:
    - name: http-grafana
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 30094
